version: '3.1'
services:
  db:
    image: mysql
    container_name: mysql_spring-store
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - spring-store_data:/var/lib/mysql

volumes:
  spring-store_data: